orgweb/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^profile/$', views.profile, name="profile"),
    url(r'^profile/(?P<user_id>\w{0,50})/$', views.profile, name="profile"),
    url(r'^edit/(?P<file_name>\w{0,50})/$', views.edit, name="org_edit"),
    url(r'^create/$', views.create, name="org_create"),
    url(r'^view/(?P<file_name>)/$', views.view, name="org_view"),
    url(r'^delete/([0-9]\w+)/$', views.delete, name="org_delete"),
]

project/urls.py
from __future__ import unicode_literals

from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.views.i18n import set_language

from mezzanine.core.views import direct_to_template
from mezzanine.conf import settings

import mezzanine

admin.autodiscover()

# Add the urlpatterns for any custom Django applications here.
# You can also change the ``home`` view to add your own functionality
# to the project's homepage.

urlpatterns = i18n_patterns(
    # Change the admin prefix here to use an alternate URL for the
    # admin interface, which would be marginally more secure.
    url("^admin/", include(admin.site.urls)),
)

if settings.USE_MODELTRANSLATION:
    urlpatterns += [
        url('^i18n/$', set_language, name='set_language'),
    ]

urlpatterns += [
    # We don't want to presume how your homepage works, so here are a
    # few patterns you can use to set it up.

    # HOMEPAGE AS STATIC TEMPLATE
    # ---------------------------
    # This pattern simply loads the index.html template. It isn't
    # commented out like the others, so it's the default. You only need
    # one homepage pattern, so if you use a different one, comment this
    # one out.

    # url("^$", direct_to_template, {"template": "index.html"}, name="home"),

    # HOMEPAGE AS AN EDITABLE PAGE IN THE PAGE TREE
    # ---------------------------------------------
    # This pattern gives us a normal ``Page`` object, so that your
    # homepage can be managed via the page tree in the admin. If you
    # use this pattern, you'll need to create a page in the page tree,
    # and specify its URL (in the Meta Data section) as "/", which
    # is the value used below in the ``{"slug": "/"}`` part.
    # Also note that the normal rule of adding a custom
    # template per page with the template name using the page's slug
    # doesn't apply here, since we can't have a template called
    # "/.html" - so for this case, the template "pages/index.html"
    # should be used if you want to customize the homepage's template.
    # NOTE: Don't forget to import the view function too!

    url("^$", mezzanine.pages.views.page, {"slug": "/"}, name="home"),

    # HOMEPAGE FOR A BLOG-ONLY SITE
    # -----------------------------
    # This pattern points the homepage to the blog post listing page,
    # and is useful for sites that are primarily blogs. If you use this
    # pattern, you'll also need to set BLOG_SLUG = "" in your
    # ``settings.py`` module, and delete the blog page object from the
    # page tree in the admin if it was installed.
    # NOTE: Don't forget to import the view function too!

    # url("^$", mezzanine.blog.views.blog_post_list, name="home"),

    # orgweb urls
    url(r'^orgweb/', include("orgweb.urls")),

    # MEZZANINE'S URLS
    # ----------------
    # ADD YOUR OWN URLPATTERNS *ABOVE* THE LINE BELOW.
    # ``mezzanine.urls`` INCLUDES A *CATCH ALL* PATTERN
    # FOR PAGES, SO URLPATTERNS ADDED BELOW ``mezzanine.urls``
    # WILL NEVER BE MATCHED!

    # If you'd like more granular control over the patterns in
    # ``mezzanine.urls``, go right ahead and take the parts you want
    # from it, and use them directly below instead of using
    # ``mezzanine.urls``.
    url("^", include("mezzanine.urls")),

    # MOUNTING MEZZANINE UNDER A PREFIX
    # ---------------------------------
    # You can also mount all of Mezzanine's urlpatterns under a
    # URL prefix if desired. When doing this, you need to define the
    # ``SITE_PREFIX`` setting, which will contain the prefix. Eg:
    # SITE_PREFIX = "my/site/prefix"
    # For convenience, and to avoid repeating the prefix, use the
    # commented out pattern below (commenting out the one above of course)
    # which will make use of the ``SITE_PREFIX`` setting. Make sure to
    # add the import ``from django.conf import settings`` to the top
    # of this file as well.
    # Note that for any of the various homepage patterns above, you'll
    # need to use the ``SITE_PREFIX`` setting as well.

    # ("^%s/" % settings.SITE_PREFIX, include("mezzanine.urls"))

]

# Adds ``STATIC_URL`` to the context of error pages, so that error
# pages can use JS, CSS and images.
handler404 = "mezzanine.core.views.page_not_found"
handler500 = "mezzanine.core.views.server_error"

orgweb/models.py
from __future__ import unicode_literals

from django.db import models


class Profile(models.Model):
    user = models.OneToOneField("auth.User")
    #date_of_birth = models.DateField(null=True)
    bio = models.TextField()


class OrgModel(models.Model):
    title = models.CharField(max_length=240)
    description = models.TextField(blank=True, null=True, max_length=240)
    user = models.ForeignKey("Profile")

    class Meta:
        ordering = ['title']


class Header(models.Model):
    title = models.CharField(max_length=240)
    level = models.IntegerField()
    parent = models.ForeignKey('OrgModel')

orgweb/forms.py
from django.forms import ModelForm
from .models import OrgModel


class OrgForm(ModelForm):
    class Meta:
        model = OrgModel
        fields = ['title', 'description']

orgweb/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.messages import info
from django.contrib.auth.decorators import login_required
from .models import Profile, OrgModel
from .forms import OrgForm

from django.shortcuts import redirect
from django.template.response import TemplateResponse
from django.core.urlresolvers import NoReverseMatch
import json


def profile(request, **kwargs):
    """
    user_id can be a private key or a string
    :param request:
    :param user_id:
    :return:
    """
    context = {}
    return render(request, 'orgweb/profile.html', context)

@login_required
def create(request):
    return render(request, 'orgweb/org_create.html', context={})


def edit(request, file_name, template='orgweb/edit.html'):
    """
    Takes file name, and performs the desired changes in the database. NOTE: This was originally
    desired to have JSON functionality, so that the interface could be fully js (no reloads).
    Fuck that.
    Now, it's only url and redirection based (MAYBE modals). In the future, maybe I will API-ize it,
    to serve both purposes.
    :param request:
    :param file_name:
    :return:
    """
    org_file, created = OrgModel.objects.get_or_create(title=file_name, user=request.user.profile)
    form = OrgForm(request.POST or None, instance=org_file)
    print request.method
    if request.method == 'POST' and form.is_valid():
        org_file = form.save()
        info(request, "orgfile updated")
        return redirect("org_edit", file_name=org_file.title)
    context = {'form': form, 'title': "Edit File", 'file': org_file}
    return TemplateResponse(request, template, context)

@login_required
def delete(request, orgfile):
    orgf = OrgModel.objects.get(pk=orgfile)
    if request.user.profile == orgf.user:
        t = orgf.title
        orgf.delete()
        info(request, t + ' has been removed', extra_tags='success')
    else:
        info(request, "you do not have permission to remove this object", extra_tags='warning')
    return render(request, "orgweb/org_create.html", context={})


def view(request):
    pass


#### EXAMPLE JSON ENCODING
#[{
# 	"title": "test",
# 	"children": {
# 		"type": "header",
# 		"title": "test",
# 		"level": "2",
# 		"children": {
# 			"type": "header",
# 			"title": "child",
# 			"level": 4
# 		}
#  	}
#}]
# HEADER properties:
#

orgweb/templates/accounts/includes/user_panel.html
{% load i18n mezzanine_tags accounts_tags %}

{% if request.user.is_authenticated %}
    <p>
    {% trans "Logged in as: " %}
    {% url "profile" request.user.username as profile_url %}
    {% if profile_url %}
        <a href="{{ profile_url }}">{{ request.user|username_or:"email" }}</a>
    </p>
        <a href="{% url "profile_update" %}" class="btn btn-default btn-sm btn-account">
            <span class="glyphicon glyphicon-edit"></span> {% trans "Update profile" %}</a>
    {% else %}
        <a href="{% url "profile_update" %}">{{ request.user|username_or:"email" }}</a>
    </p>
    {% endif %}
    <a href="{% url "logout" %}{# ?next={{ request.path }} #}" class="btn btn-sm btn-danger btn-account">
        <span class="glyphicon glyphicon-log-out"></span> {% trans "Log out" %}</a>
{% else %}
    <a href="{% url "login" %}?next={{ request.path }}" class="btn btn-default btn-sm btn-account">
        <span class="glyphicon glyphicon-log-in"></span> {% trans "Log in" %}</a>
    &nbsp;{% trans "or" %}&nbsp;
    <a href="{% url "signup" %}?next={{ request.path }}" class="btn btn-default btn-sm btn-account">
        <span class="glyphicon glyphicon-edit"></span> {% trans "Sign up" %}</a>
{% endif %}

orgweb/templates/base.html
<!doctype html>
<html lang="{{ LANGUAGE_CODE }}"{% if LANGUAGE_BIDI %} dir="rtl"{% endif %}>
{% load pages_tags mezzanine_tags i18n staticfiles %}

<head>
<meta http-equiv="Content-type" content="text/html; charset=utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="keywords" content="{% block meta_keywords %}{% endblock %}">
<meta name="description" content="{% block meta_description %}{% endblock %}">
<title>{% block meta_title %}{% endblock %}{% if settings.SITE_TITLE %} | {{ settings.SITE_TITLE }}{% endif %}</title>
<link rel="shortcut icon" href="{% static "img/favicon.ico" %}">

{% ifinstalled mezzanine.blog %}
<link rel="alternate" type="application/rss+xml" title="RSS" href="{% url "blog_post_feed" "rss" %}">
<link rel="alternate" type="application/atom+xml" title="Atom" href="{% url "blog_post_feed" "atom" %}">
{% endifinstalled %}

{% compress css %}
<link rel="stylesheet" href="{% static "css/bootstrap.css" %}">
<link rel="stylesheet" href="{% static "css/mezzanine.css" %}">
<link rel="stylesheet" href="{% static "css/bootstrap-theme.css" %}">
{% if LANGUAGE_BIDI %}
<link rel="stylesheet" href="{% static "css/bootstrap-rtl.css" %}">
{% endif %}
{% ifinstalled cartridge.shop %}
<link rel="stylesheet" href="{% static "css/cartridge.css" %}">
{% if LANGUAGE_BIDI %}
<link rel="stylesheet" href="{% static "css/cartridge.rtl.css" %}">
{% endif %}
{% endifinstalled %}
{% block extra_css %}{% endblock %}
{% endcompress %}

{% compress js %}
<script src="{% static "mezzanine/js/"|add:settings.JQUERY_FILENAME %}"></script>
<script src="{% static "js/bootstrap.js" %}"></script>
<script src="{% static "js/bootstrap-extras.js" %}"></script>
{% block extra_js %}{% endblock %}
{% endcompress %}

<!--[if lt IE 9]>
<script src="{% static "js/html5shiv.js" %}"></script>
<script src="{% static "js/respond.min.js" %}"></script>
<![endif]-->

{% block extra_head %}{% endblock %}
</head>

<body id="{% block body_id %}body{% endblock %}">

<div class="navbar navbar-default navbar-fixed-top" role="navigation">
<div class="container">
<div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">{% trans "Toggle Navigation" %}</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
    {% block navbar_title %}
    {% if settings.SITE_TITLE %}<a class="navbar-brand" href="/">{{ settings.SITE_TITLE }}</a>{% endif %}
    {% if settings.SITE_TAGLINE %}<p class="navbar-text visible-lg">{{ settings.SITE_TAGLINE }}</p>{% endif %}
    {% endblock%}
</div>
<div class="navbar-collapse collapse">
    {% block navbar_search_form %}{% search_form "all" %}{% endblock %}
    {% block navbar_dropdown_menu %}{% page_menu "pages/menus/dropdown.html" %}{% endblock%}
</div>
</div>
</div>

<div class="container">

{% nevercache %}
{% if messages %}
<div class="messages">
{% for message in messages %}
<div class="alert alert-dismissable alert-{{ message.tags }}" data-alert="alert">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    {{ message }}
</div>
{% endfor %}
</div>
{% endif %}
{% endnevercache %}

<h1>{% block title %}{% endblock %}</h1>

<ul class="breadcrumb">
{% spaceless %}
{% block breadcrumb_menu %}{% page_menu "pages/menus/breadcrumb.html" %}{% endblock %}
{% endspaceless %}
</ul>

</div>

<div class="container">
<div class="row">

<div class="col-md-2 left">
    {% block left_panel %}
    <div class="panel panel-default tree">
    {% include 'orgweb/menus/sidebar_tree.html' %}
    </div>
    {% endblock %}
</div>


<div class="col-md-7 middle">
    {% block main %}{% endblock %}
</div>

<div class="col-md-3 right">
    {% nevercache %}
    {% include "includes/language_selector.html" %}
    {% include "includes/user_panel.html" %}
    {% endnevercache %}
    <div class="panel panel-default">
    <div class="panel-body">
    {% block right_panel %}
    {% ifinstalled mezzanine.twitter %}
    {% include "twitter/tweets.html" %}
    {% endifinstalled %}
    {% endblock %}
    </div>
    </div>
</div>

</div>
</div>

<footer>
<div class="container">
{% page_menu "pages/menus/footer.html" %}

<div class="row">
<p class="site-info text-center">
    {% trans "Powered by" %}
    <a href="http://mezzanine.jupo.org">Mezzanine</a>{% ifinstalled cartridge.shop %},
    <a href="http://cartridge.jupo.org">Cartridge</a>{% endifinstalled %}
    {% trans "and" %}
    <a href="http://www.djangoproject.com">Django</a>
    <span class="separator">|</span>
    {% trans "Theme by" %} <a target="_blank" href="http://getbootstrap.com">Bootstrap</a>
    {% ifinstalled mezzanine.mobile %}
    <span class="separator">|</span>
    <a href="{% url "set_device" "mobile" %}?next={{ request.path }}">{% trans "View Mobile Site" %}</a>
    {% endifinstalled %}
</p>
</div>
</div>
</footer>

{% block footer_js %}
{% include "includes/footer_scripts.html" %}
{% endblock %}

</body>
</html>

orgweb/templates/orgweb/edit.html
{% extends 'base.html' %}
{% load mezzanine_tags %}

{% block title %}{{ file.title }}{% endblock %}

{% block main %}
{% if created %}
    <h4>created new orgfile</h4>
{% endif %}

{% errors_for form %}

<form action="/orgweb/edit/{{ file.title }}/" method="post">
  <fieldset>
    <legend></legend>
      {% fields_for form %}
        <div class="form-actions">
          <input type="submit" value="Submit" class="btn btn-primary btn-large" />
        </div>
  </fieldset>
</form>
{% endblock %}

orgweb/templates/orgweb/index.html
{% extends "base.html" %}

orgweb/templates/orgweb/menus/sidebar_tree.html
{% load pages_tags %}

{% spaceless %}
{% if request.user.is_authenticated %}
<ul class="nav nav-list ">
    {% for orgfile in request.user.profile.orgmodel_set.all %}
    <li {% if orgfile.title == file.title %}class="active"{% endif %}>
      <a href="{% url "org_edit" orgfile.title %}">{{ orgfile.title }}</a>
    </li>
    {% endfor %}
</ul>
{% else %}
    {% page_menu 'pages/menus/tree.html' %}
{% endif %}
{% endspaceless %}

orgweb/templates/orgweb/org_create.html
{% extends "base.html" %}
{% load i18n %}
{% block main %}

{% if request.user.profile.orgmodel_set %}
    <ul class="list-group">
    {% for file in request.user.profile.orgmodel_set.all %}
    <li class="list-group-item">
        {{ file.title }}
        <a href="{% url "org_delete" file.pk %}" class="btn btn-danger btn-sm pull-right">
            {% trans "Delete" %} <span class="glyphicon glyphicon-remove"></span></a>
    </li>
    {% endfor %}
    </ul>
{% else %}
    <p>{{ request.user.username }} has no orgfiles</p>
{% endif %}

<form action="{% url "org_edit" %}" id="create-org-form">
{% csrf_token %}
  <div class="input-group">
    <input type="text" class="form-control" id="create-org-input" placeholder="New file..." aria-describedby="basic-addon2">
    <span class="input-group-addon" id="basic-addon2">.org</span>
  </div>
</form>

{% endblock %}

{% block footer_js %}

<script type="text/javascript">
$( "#create-org-form").submit(function( event ) {

    event.preventDefault();
    var $form = $( this),
            title = $form.find( "input[id='create-org-input']").val(),
            url = $form.attr( "action" );

    var orgfile = { title : title };
    var posting = $.post( url, {
        orgfile: JSON.stringify(orgfile),
        csrfmiddlewaretoken: document.getElementsByName('csrfmiddlewaretoken')[0].value,
        dataType : "json"
    });

    posting.done(function( data, statusText, xhr ) {
        console.log(data);
        if (xhr.status == 200) {
            console.log("success");
            $form.find( "div[class='input-group']").animate({
                opacity: 0
            }, 500, function() {
               console.log("animation complete");
               window.location.replace("{% url 'org_create' %}");
            });
        }
    });

});
</script>
{% endblock %}

orgweb/templates/orgweb/profile.html
{% extends "base.html" %}
{% load i18n %}

{% block main %}
{% if request.user.is_authenticated %}
        <div class="list-group">
        {% if request.user.orgmodel_set.all %}
            {% for file in request.user.orgmodel_set.all %}
              <div class="list-group-item">
                <h4 class="list-group-item-heading">{{ file.title }}</h4>
                <p class="list-group-item-text">{{ file.description }}</p>

                <a href="#" class="btn btn-primary">edit</a>

              </div>
            {% endfor %}
        {% else %}
        <div class="list-group-item">
            <h1 class="list-group-item-heading">Looks like you don't have any org files. <a href="{% url "org_create" %}" class="btn btn-success btn-md btn-account">
            <span class="glyphicon glyphicon-edit"></span> {% trans "Get organized" %}</a>
            </h1>
        </div>
        {% endif %}
{% else %}
<div>
    <p>{{ request.user.username }} has {{ request.user.orgmodel_set.all|length }} orgfile{{ request.user.orgmodel_set.all|length|pluralize }}</p>
</div>
{% endif %}
</div>
{% endblock %}

orgweb/templates/pages/index.html
{% extends "pages/richtextpage.html" %}
{% load pages_tags %}
{% block title %}{{ page.title }}{% endblock %}

{% block main %}
{#{{ block.super }}#}
{% if user.is_authenticated %}
    <h1>Hello {{ request.user.username }}</h1>
    <h4>Here are your tasks for today:</h4>
{% endif %}
{% endblock %}